version: '3'
name: laravel-project

services:

    ####################################################################################################
    # PHP
    ####################################################################################################
    php:
        context: ${PWD}/.docker/php
        dockerfile: Dockerfile
        ports:
            - 5173:5173
        volumes:
            - .:/var/www:cached

    ####################################################################################################
    # Nginx
    ####################################################################################################
    nginx:
        image: nginx
        ports:
            - 80:80
        volumes:
            - .:/var/www
            - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - php
