services:
  - type: web
    name: laravel-app
    env: docker
    buildCommand: docker build -t laravel-app .
    startCommand: docker run -p 80:80 laravel-app
    envVars:
      - key: APP_KEY
        generateValue: true
      - key: APP_ENV
        value: production
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromDatabase:
          name: laravel-mysql
          property: host
      - key: DB_DATABASE
        fromDatabase:
          name: laravel-mysql
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: laravel-mysql
          property: username
      - key: DB_PASSWORD
        fromDatabase:
          name: laravel-mysql
          property: password

databases:
  - name: laravel-mysql
    plan: starter